basic.forever(function () {
    music.playTone(466, music.beat(BeatFraction.Double))
    music.playTone(370, music.beat(BeatFraction.Double))
    music.playTone(466, music.beat(BeatFraction.Double))
    music.playTone(370, music.beat(BeatFraction.Double))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(370, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Double))
    basic.pause(1000)
    music.playTone(466, music.beat(BeatFraction.Double))
    basic.pause(1000)
    music.playTone(233, music.beat(BeatFraction.Double))
    music.playTone(185, music.beat(BeatFraction.Double))
    music.playTone(233, music.beat(BeatFraction.Double))
    music.playTone(185, music.beat(BeatFraction.Whole))
    music.playTone(208, music.beat(BeatFraction.Whole))
    music.playTone(208, music.beat(BeatFraction.Whole))
    music.playTone(233, music.beat(BeatFraction.Whole))
    music.playTone(208, music.beat(BeatFraction.Whole))
    music.playTone(185, music.beat(BeatFraction.Double))
    music.playTone(185, music.beat(BeatFraction.Whole))
    music.setVolume(556544321)
})
